### PR TITLE
ci: website preview

### PR DESCRIPTION
**Pull request by yetist**
We can create PR here, and see the preview from mate-wiki-pre.

If commit or merge some code into the master branch, https://wiki.mate-desktop.org is automatically updated.

### CODE REVIEW

**Comment by yetist** [comment]
The test PR is here: https://github.com/yetist/mate-wiki/pull/1

**Comment by yetist** [comment]
@raveit65 

Please enable Travis CI for this repo, and update the GITHUB_TOKEN environment.

**Comment by raveit65** [comment]
Done, this repo is enabled at travis and i setup a GITHUB_TOKEN
Do we need the same for `mate-wiki-pre` repo?

**Comment by yetist** [comment]
Well, everything will be fine, let us forget the mate-wiki-pre repo, there is no need to do anything on mate-wiki-pre.

**Comment by yetist** [comment]
@raveit65 

I created #5 to test the preview, and it works.

**Comment by raveit65** [comment]
Cool :)
For better understanding. How will the mate-wiki-pre repo be updated (synced) with merged PRs from main wiki repo?

**Comment by raveit65** [comment]
Ahh, i see this repo is empty now, only a `.md` file is there for information.

**Comment by raveit65** [comment]
Thanks again for your code.

**Comment by yetist** [comment]
The only function of mate-wiki-pre is to use the gh-pages branch to display the preview.

All commit and PRs are in the master branch of mate-wiki, and the gh-pages branch of mate-wiki can also be safely deleted.

In other words, anything commit into the master branch of mate-wiki will directly update the official website.

**Comment by yetist** [comment]
If someone creates a PR, all content on this branch will be transferred to the gh-pages branch of mate-wiki-pre, which is what the preview site can see.

If PR is merged into the master branch, the official website will be updated.

**Comment by raveit65** [comment]
Thanks for explanation.
So, gh-pages from make-wiki use now master branch to publish our wiki.
I will delete gh-pages branch from make-wiki repo to avoid confusion.

**Comment by yetist** [comment]
Maybe change the repo's name from `mate-wiki-pre` to `mate-wiki-preview` will be better?

**Comment by raveit65** [comment]
@yetist 
Done.

**Pull request merged**
