### PR TITLE
Add a starting guide about how to debug with eclipse

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by rbuj** [comment]
Feel free to edit and change the content. Happy hacking!

**Comment by selectiveduplicate** [comment]
@rbuj How do I test this using MDwiki? Sorry but I'm not familiar with it.

**Comment by raveit65** [comment]
@selectiveduplicate 
At the moment we don't have a preview like our website for our wiki.
So , we have to review it by hand to avoid html errors.
Our wiki is located at https://wiki.mate-desktop.org/#!index.md

@rbuj 
At mate wiki main page we have already a debug link which pointed to https://wiki.mate-desktop.org/#!pages/debug.md
You should add a link for eclipse-debug to main wiki site.
Or we need a new debug page with 2 parts
- old debug
- eclipce debug

**Comment by raveit65** [comment]
see https://github.com/mate-desktop/mate-wiki/issues/2 for more infos about missing preview page.

**Comment by rbuj** [comment]
@raveit65 
OK, then we can freeze this PR. I will try to expand the existing page by adding new content, then we will analyze if it's better to split it into small parts. I will write something about logging, debugging, profiling and tracing MATE components.

**Review by lukefromdc — APPROVED** [review]
While I've never used an IDE like Eclipse, this looks very nicely written. No idea if there are technical errors in it,  but this walks people though the how-to of doing something

**Comment by yetist** [comment]
@rbuj 

Please rebase on the master branch, so we can see the preview.

**Comment by rbuj** [comment]
@yetist done

**Comment by yetist** [comment]
It's hard to see the new page, add a link on exists page will be better.

**Comment by rbuj** [comment]
@yetist I added a link pointing to the new page in index.md but it doesn't apper on the preview.

**Comment by raveit65** [comment]
I get a firefox warning with `https://wiki.mate-desktop.dev/#!pages/debug-eclipse.md`.
A website will slow down your web-browser. Stop website or waiting?

**Comment by yetist** [comment]
~~It seems that travis did not add the new file into gh-pages branch of mate-wiki-pre.~~

**Comment by yetist** [comment]
I think the mdwiki dosen't support some markdown format, like "```shell", if remove the "shell" chars, it can show me the page.

**Comment by yetist** [comment]
@rbuj 

Please see my test here: https://github.com/yetist/mate-wiki/pull/3, The markdown file need some empty lines.

**Comment by yetist** [comment]
I created a new branch to test this repo, and everything is ok.

https://github.com/mate-desktop/mate-wiki/tree/just-test
https://wiki.mate-desktop.dev/#!pages/new-page.md

So, the contents of the debug-eclipse.md have some errors, but I don't know more.

**Comment by rbuj** [comment]
Now it seems it works. Test:
- https://wiki.mate-desktop.dev/#!index.md
- https://wiki.mate-desktop.dev/#!pages/debug-eclipse.md

**Review by raveit65 — APPROVED** [review]
LGTM.
Nice work and it looks like something i will use in the next weeks ;)

**Pull request merged**
