### PR TITLE
add new mate-wiki website

### PR DESCRIPTION
**Pull request by mbkma**
This is a proposal for a new mate-wiki website, as discussed before. Maybe it is easier to create a new repo with the content of https://github.com/mbkma/mbkma.github.io (only the url would need to be changed). You can look at the new wiki proposal here: https://mbkma.github.io/

### CODE REVIEW

**Comment by raveit65** [comment]
@mbkma 
We have file conflicts.
Maybe because of last commit in master?

**Comment by mbkma** [comment]
@raveit65 The main branch in https://github.com/mbkma/mbkma.github.io is the `source` branch. There is a travis job that runs on every push to the `source` branch and deploys the website to the main branch.
I fear that if I make a PR that the main branch gets overwritten by this travis job. Maybe it is simpler to just make a new mate-wiki repo from my personal repo if you agree to use the new website?

**Comment by raveit65** [comment]
> I fear that if I make a PR that the main branch gets overwritten by this travis job.

No, nothing will be over written in wiki repo. The deployment goes to the mate-wiki-preview repo. https://github.com/mate-desktop/mate-wiki-preview
See https://github.com/mate-desktop/mate-wiki/blob/master/.travis.yml#L40
```
deploy:
  #preview website
  - provider: pages
    edge: true
    token: $GITHUB_TOKEN
    keep_history: false
    repo: mate-desktop/mate-wiki-preview
<cut>
```
We did that to see a preview of PRs before merging. In result we should see the new wiki design in a preview of this PR when deployment at travis is successful.
I guess this is what we want, or not?  :)

**Comment by mbkma** [comment]
The problem is the travis job, which I set up for the new wiki: https://github.com/mbkma/mbkma.github.io/blob/58c85c066cd36530a26bf02c0a62094206d48955/.github/workflows/on-commit.yml#L31
This may overwrite the master branch if I do a PR...
For the new wiki we would not need an external wiki-preview repo, because it can be previewed locally.

**Comment by raveit65** [comment]
Ok, got it. 
After reading https://github.com/mbkma/mbkma.github.io/tree/58c85c066cd36530a26bf02c0a62094206d48955#readme
it seems that this wiki is only hosted by gh-pages? The old one is hosted by our website https://wiki.mate-desktop.org/#!index.md
Ok, this shouldn't be a problem. But it should be possible to use `https://wiki.mate-desktop.org` as custom domain for gh-pages?
To avoid to rewrite all wiki links on our website.

> For the new wiki we would not need an external wiki-preview repo, because it can be previewed locally.

Locally means i have to generate the page by hand?
Isn't that a step back :)

**Comment by mbkma** [comment]
As far as I can see the current mate-wiki only uses github-pages as well https://github.com/mate-desktop/mate-wiki/settings (see Github Pages heading). 

>     For the new wiki we would not need an external wiki-preview repo, because it can be previewed locally.
> 
> Locally means i have to generate the page by hand?
> Isn't that a step back :)

Yes, I have to think about how to deploy pull requests to another branch.

**Comment by raveit65** [comment]
> As far as I can see the current mate-wiki only uses github-pages as well ...

Yes this what we need to do for new wiki.

> Yes, I have to think about how to deploy pull requests to another branch.

Or we do the same for preview like the old one. The problem is that you have only one gh-pages site.
For that reason we used another repo for preview.
Any way, maybe you got a better idea.

Ok, i will clone your repo to wiki-new for the moment. We can rename it when everything is running and we delete the old one.

**Comment by raveit65** [comment]
@mbkma 
Done , new repo is up https://github.com/mate-desktop/mate-wiki-new
I added you as admin to the repo. You should be able now to manage all tasks.

**Comment by mbkma** [comment]
@raveit65 the new wiki is now ready to replace the old one

**Comment by raveit65** [comment]
@mbkma 
Currently our credits by travis-CI are running out. I wrote them mail but i didn't  get an answer for the moment.
I would prefer to wait when CI is running again.

**Comment by raveit65** [comment]
Opps, i forgot that we don't need travis CI to deploy the new website.
Ok, i will replace the old one.

**Comment by raveit65** [comment]
@mbkma 
I switched gh-pages to use custom domain https://wiki.mate-desktop.org/
Now it looks complete broken :/

**Comment by raveit65** [comment]
When switching to master branch gh-pages settings, it seems that it looks better, but links needs to be updated ?
https://mate-desktop.github.io/mate-wiki-new/ to https://wiki.mate-desktop.org/ ?
Also, i renamed mate-wiki-new to mate-wiki.
Old wiki is renamed to mate-wiki-old. So we can switch back if necessary.

**Comment by raveit65** [comment]
Switched back to use gh-pages, but something is wrong when using custom link "wiki.mate-desktop.org"
Edit:
Seems links needs to be fixed now https://github.com/mate-desktop/mate-wiki/blob/master/config.toml

**Comment by mbkma** [comment]
@raveit65 maybe it is because you can not have 2 CNAME files pointing to the same link:

> The domain name must be unique across all GitHub Pages sites. For example, if another repository's CNAME file contains example.com, you cannot use example.com in the CNAME file for your repository.
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages

Maybe remove CNAME file in mate-wiki-old?

**Comment by raveit65** [comment]
Terminated!
https://github.com/mate-desktop/mate-wiki-old/commit/cc1fd0e7468cc7aef375c4aca8a0d8399276de22

**Comment by raveit65** [comment]
It works https://wiki.mate-desktop.org/
Thank you for reading docs :)

**Comment by raveit65** [comment]
There is an edit button in the new wiki. Who will see this button, btw. can edit the pages?
Hopefully only people who have already acls of github repo.
How we handle the preview of PRs? Same like old wiki?
Edit:
I like the dark mode of new wiki page :)

**Comment by mbkma** [comment]
Everyone can see it, but for people without access, this will appear:

proof

I have not thought about the previews yet. I think it is not very urgent, because every PR is tested to compile properly by github actions. And the changes will mostly be adding text to markdown files, nothing major...
But when I have more time I can look into that.

**Pull request closed without merging**
